server:
  port: 8082
  
 
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservice
    username: postgres
    password: root
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    
  application:
    name: Hotel-Service 
    
  config:
    import: configserver:http://localhost:8085    
    
    
#eureka:
#  instance:
#    prefer-ip-address: true
#    
#client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
  
   
